=begin
#Akeyless API

#The purpose of this application is to provide access to Akeyless API.

The version of the OpenAPI document: 2.0
Contact: support@akeyless.io
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.0.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Akeyless::CreateAuthMethodK8SOutput
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Akeyless::CreateAuthMethodK8SOutput do
  let(:instance) { Akeyless::CreateAuthMethodK8SOutput.new }

  describe 'test an instance of CreateAuthMethodK8SOutput' do
    it 'should create an instance of CreateAuthMethodK8SOutput' do
      expect(instance).to be_instance_of(Akeyless::CreateAuthMethodK8SOutput)
    end
  end
  describe 'test attribute "access_id"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "prv_key"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
