=begin
#Akeyless API

#The purpose of this application is to provide access to Akeyless API.

The version of the OpenAPI document: 2.0
Contact: support@akeyless.io
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.0.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Akeyless::UpdateDBTargetOutput
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Akeyless::UpdateDBTargetOutput do
  let(:instance) { Akeyless::UpdateDBTargetOutput.new }

  describe 'test an instance of UpdateDBTargetOutput' do
    it 'should create an instance of UpdateDBTargetOutput' do
      expect(instance).to be_instance_of(Akeyless::UpdateDBTargetOutput)
    end
  end
  describe 'test attribute "target_id"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
