=begin
#Akeyless API

#The purpose of this application is to provide access to Akeyless API.

The version of the OpenAPI document: 2.0
Contact: support@akeyless.io
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.4.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Akeyless::AccountObjectVersionSettingsOutput
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Akeyless::AccountObjectVersionSettingsOutput do
  let(:instance) { Akeyless::AccountObjectVersionSettingsOutput.new }

  describe 'test an instance of AccountObjectVersionSettingsOutput' do
    it 'should create an instance of AccountObjectVersionSettingsOutput' do
      expect(instance).to be_instance_of(Akeyless::AccountObjectVersionSettingsOutput)
    end
  end
  describe 'test attribute "default_versioning"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "items"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
