=begin
#Akeyless API

#The purpose of this application is to provide access to Akeyless API.

The version of the OpenAPI document: 2.0
Contact: support@akeyless.io
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.4.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Akeyless::GatewayStopProducerOutput
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Akeyless::GatewayStopProducerOutput do
  let(:instance) { Akeyless::GatewayStopProducerOutput.new }

  describe 'test an instance of GatewayStopProducerOutput' do
    it 'should create an instance of GatewayStopProducerOutput' do
      expect(instance).to be_instance_of(Akeyless::GatewayStopProducerOutput)
    end
  end
  describe 'test attribute "producer_name"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
