=begin
#Akeyless API

#The purpose of this application is to provide access to Akeyless API.

The version of the OpenAPI document: 2.0
Contact: support@akeyless.io
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.4.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Akeyless::GatewayUpdateProducerAwsOutput
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Akeyless::GatewayUpdateProducerAwsOutput do
  let(:instance) { Akeyless::GatewayUpdateProducerAwsOutput.new }

  describe 'test an instance of GatewayUpdateProducerAwsOutput' do
    it 'should create an instance of GatewayUpdateProducerAwsOutput' do
      expect(instance).to be_instance_of(Akeyless::GatewayUpdateProducerAwsOutput)
    end
  end
  describe 'test attribute "producer_details"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
